<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>list_RecordsFound</name>
   <tag></tag>
   <elementGuidId>036bc158-6ce0-49bc-bc2f-c4d82d45dd0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.orangehrm-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div[2]/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a1ce47ca-d912-4a07-bc89-f6673355557f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-container</value>
      <webElementGuid>d1f15ad6-8bb8-4faa-a9f2-c7345fac40fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IdAscendingDescendingFirst (&amp; Middle) NameAscendingDescendingLast NameAscendingDescendingJob TitleAscendingDescendingEmployment StatusAscendingDescendingSub UnitAscendingDescendingSupervisorAscendingDescendingActions0251777Andrei VlademirIonescu0253777Andrei VlademirIonescu0070Anthony NolanSales RepresentativeFull-Time ProbationSalesLinda Anderson0046Cassidy HopeIT ManagerPart-Time ContractTechOpsOdis Adalwin0204Cecil BonaparteSoftware EngineerFull-Time PermanentDevelopmentFiona Grace0212Charlie CarterQA EngineerFull-Time ProbationQuality Assurance0217Chenzira ChukiQA EngineerFull-Time PermanentQuality Assurance0066David MorrisAccount AssistantFull-Time PermanentFinanceKevin Mathews0020Dominic ChaseVP - Client ServicesFull-Time PermanentAdministrationJohn Smith0227Ehioze EboAccount AssistantFull-Time ProbationFinanceKevin Mathews0029Fiona GraceSoftware ArchitectFull-Time PermanentDevelopmentOdis Adalwin0099Garry WhiteHR AssociateFull-Time PermanentHuman ResourcesPaul Collings0235Goutam GaneshSales RepresentativeFull-Time PermanentSalesLinda AndersonKA17INDIA K A0095Jacqueline WhiteSupport SpecialistFull-Time ContractTechnical SupportDominic Chase0243Jadine JackieHR AssociateFull-Time ProbationHuman ResourcesPaul Collings0062Jasmine MorganFinancial AnalystFull-Time ProbationFinanceKevin Mathews0083Joe RootContent SpecialistFull-Time ProbationMarketingMelan Peiris0011John SmithChief Executive OfficerFull-Time PermanentAdministration0054Jordan MathewsDatabase AdministratorFull-Time ContractTechOpsCassidy Hope0254Jyoti Jadhav0058Kevin MathewsFinance ManagerFull-Time PermanentFinancePeter Anderson0239Kiyara HuHR AssociateFull-Time PermanentHuman ResourcesPaul Collings0257lambert lambert0016Linda JaneAndersonVP - Sales &amp; MarketingFull-Time PermanentAdministrationJohn Smith0208Lisa AndrewsSoftware EngineerFull-Time ProbationDevelopmentFiona Grace0091Luke WrightHead of SupportFull-Time PermanentTechnical SupportDominic Chase0050Maggie ManningNetwork AdministratorFull-Time ProbationTechOpsCassidy Hope0078Melan PeirisSocial Media MarketerFull-Time PermanentMarketingLinda Andersonmohan kIT Manager0231Nathan ElliotSales RepresentativeFull-Time ProbationSalesLinda Anderson0074Nina PatelPre-Sales CoordinatorFull-Time ContractSalesAnthony Nolan0002Odis AdalwinChief Technical OfficerFull-Time PermanentAdministrationJohn Smith0001Orange Test0024Paul CollingsHR ManagerFull-Time PermanentHuman ResourcesJohn Smith0007Peter MacAndersonChief Financial OfficerFull-Time ProbationAdministrationJohn Smith0247Rahul MulgePatil3322Ravi MB0042Rebecca HarmonyQA EngineerFull-Time ContractQuality Assurance0034Russel HamiltonSoftware EngineerFull-Time PermanentDevelopmentFiona Grace0087Sania ShaheenCustomer Success ManagerFull-Time PermanentTechnical SupportDominic Chase0103Sara TencradyPayroll AdministratorFull-Time PermanentHuman ResourcesPaul Collings0249Virat Kohli</value>
      <webElementGuid>9671cdee-089c-4004-aacc-7c7b76785c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]/div[@class=&quot;orangehrm-paper-container&quot;]/div[@class=&quot;orangehrm-container&quot;]</value>
      <webElementGuid>ffda4e09-ca5f-497b-a088-a07fd75f8c1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div[2]/div[3]</value>
      <webElementGuid>1cd1cc62-6aed-4cc5-880b-2ba25692405b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[3]</value>
      <webElementGuid>3687303f-82df-4c43-83ab-f060d56a7bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'IdAscendingDescendingFirst (&amp; Middle) NameAscendingDescendingLast NameAscendingDescendingJob TitleAscendingDescendingEmployment StatusAscendingDescendingSub UnitAscendingDescendingSupervisorAscendingDescendingActions0251777Andrei VlademirIonescu0253777Andrei VlademirIonescu0070Anthony NolanSales RepresentativeFull-Time ProbationSalesLinda Anderson0046Cassidy HopeIT ManagerPart-Time ContractTechOpsOdis Adalwin0204Cecil BonaparteSoftware EngineerFull-Time PermanentDevelopmentFiona Grace0212Charlie CarterQA EngineerFull-Time ProbationQuality Assurance0217Chenzira ChukiQA EngineerFull-Time PermanentQuality Assurance0066David MorrisAccount AssistantFull-Time PermanentFinanceKevin Mathews0020Dominic ChaseVP - Client ServicesFull-Time PermanentAdministrationJohn Smith0227Ehioze EboAccount AssistantFull-Time ProbationFinanceKevin Mathews0029Fiona GraceSoftware ArchitectFull-Time PermanentDevelopmentOdis Adalwin0099Garry WhiteHR AssociateFull-Time PermanentHuman ResourcesPaul Collings0235Goutam GaneshSales RepresentativeFull-Time PermanentSalesLinda AndersonKA17INDIA K A0095Jacqueline WhiteSupport SpecialistFull-Time ContractTechnical SupportDominic Chase0243Jadine JackieHR AssociateFull-Time ProbationHuman ResourcesPaul Collings0062Jasmine MorganFinancial AnalystFull-Time ProbationFinanceKevin Mathews0083Joe RootContent SpecialistFull-Time ProbationMarketingMelan Peiris0011John SmithChief Executive OfficerFull-Time PermanentAdministration0054Jordan MathewsDatabase AdministratorFull-Time ContractTechOpsCassidy Hope0254Jyoti Jadhav0058Kevin MathewsFinance ManagerFull-Time PermanentFinancePeter Anderson0239Kiyara HuHR AssociateFull-Time PermanentHuman ResourcesPaul Collings0257lambert lambert0016Linda JaneAndersonVP - Sales &amp; MarketingFull-Time PermanentAdministrationJohn Smith0208Lisa AndrewsSoftware EngineerFull-Time ProbationDevelopmentFiona Grace0091Luke WrightHead of SupportFull-Time PermanentTechnical SupportDominic Chase0050Maggie ManningNetwork AdministratorFull-Time ProbationTechOpsCassidy Hope0078Melan PeirisSocial Media MarketerFull-Time PermanentMarketingLinda Andersonmohan kIT Manager0231Nathan ElliotSales RepresentativeFull-Time ProbationSalesLinda Anderson0074Nina PatelPre-Sales CoordinatorFull-Time ContractSalesAnthony Nolan0002Odis AdalwinChief Technical OfficerFull-Time PermanentAdministrationJohn Smith0001Orange Test0024Paul CollingsHR ManagerFull-Time PermanentHuman ResourcesJohn Smith0007Peter MacAndersonChief Financial OfficerFull-Time ProbationAdministrationJohn Smith0247Rahul MulgePatil3322Ravi MB0042Rebecca HarmonyQA EngineerFull-Time ContractQuality Assurance0034Russel HamiltonSoftware EngineerFull-Time PermanentDevelopmentFiona Grace0087Sania ShaheenCustomer Success ManagerFull-Time PermanentTechnical SupportDominic Chase0103Sara TencradyPayroll AdministratorFull-Time PermanentHuman ResourcesPaul Collings0249Virat Kohli' or . = 'IdAscendingDescendingFirst (&amp; Middle) NameAscendingDescendingLast NameAscendingDescendingJob TitleAscendingDescendingEmployment StatusAscendingDescendingSub UnitAscendingDescendingSupervisorAscendingDescendingActions0251777Andrei VlademirIonescu0253777Andrei VlademirIonescu0070Anthony NolanSales RepresentativeFull-Time ProbationSalesLinda Anderson0046Cassidy HopeIT ManagerPart-Time ContractTechOpsOdis Adalwin0204Cecil BonaparteSoftware EngineerFull-Time PermanentDevelopmentFiona Grace0212Charlie CarterQA EngineerFull-Time ProbationQuality Assurance0217Chenzira ChukiQA EngineerFull-Time PermanentQuality Assurance0066David MorrisAccount AssistantFull-Time PermanentFinanceKevin Mathews0020Dominic ChaseVP - Client ServicesFull-Time PermanentAdministrationJohn Smith0227Ehioze EboAccount AssistantFull-Time ProbationFinanceKevin Mathews0029Fiona GraceSoftware ArchitectFull-Time PermanentDevelopmentOdis Adalwin0099Garry WhiteHR AssociateFull-Time PermanentHuman ResourcesPaul Collings0235Goutam GaneshSales RepresentativeFull-Time PermanentSalesLinda AndersonKA17INDIA K A0095Jacqueline WhiteSupport SpecialistFull-Time ContractTechnical SupportDominic Chase0243Jadine JackieHR AssociateFull-Time ProbationHuman ResourcesPaul Collings0062Jasmine MorganFinancial AnalystFull-Time ProbationFinanceKevin Mathews0083Joe RootContent SpecialistFull-Time ProbationMarketingMelan Peiris0011John SmithChief Executive OfficerFull-Time PermanentAdministration0054Jordan MathewsDatabase AdministratorFull-Time ContractTechOpsCassidy Hope0254Jyoti Jadhav0058Kevin MathewsFinance ManagerFull-Time PermanentFinancePeter Anderson0239Kiyara HuHR AssociateFull-Time PermanentHuman ResourcesPaul Collings0257lambert lambert0016Linda JaneAndersonVP - Sales &amp; MarketingFull-Time PermanentAdministrationJohn Smith0208Lisa AndrewsSoftware EngineerFull-Time ProbationDevelopmentFiona Grace0091Luke WrightHead of SupportFull-Time PermanentTechnical SupportDominic Chase0050Maggie ManningNetwork AdministratorFull-Time ProbationTechOpsCassidy Hope0078Melan PeirisSocial Media MarketerFull-Time PermanentMarketingLinda Andersonmohan kIT Manager0231Nathan ElliotSales RepresentativeFull-Time ProbationSalesLinda Anderson0074Nina PatelPre-Sales CoordinatorFull-Time ContractSalesAnthony Nolan0002Odis AdalwinChief Technical OfficerFull-Time PermanentAdministrationJohn Smith0001Orange Test0024Paul CollingsHR ManagerFull-Time PermanentHuman ResourcesJohn Smith0007Peter MacAndersonChief Financial OfficerFull-Time ProbationAdministrationJohn Smith0247Rahul MulgePatil3322Ravi MB0042Rebecca HarmonyQA EngineerFull-Time ContractQuality Assurance0034Russel HamiltonSoftware EngineerFull-Time PermanentDevelopmentFiona Grace0087Sania ShaheenCustomer Success ManagerFull-Time PermanentTechnical SupportDominic Chase0103Sara TencradyPayroll AdministratorFull-Time PermanentHuman ResourcesPaul Collings0249Virat Kohli')]</value>
      <webElementGuid>6549ab08-67d3-423d-bf48-e8c136d5c94d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
