<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdownList_Currency</name>
   <tag></tag>
   <elementGuidId>b18bff0b-23e6-4eab-956c-5ae74baeaaf3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.oxd-select-dropdown.--positon-bottom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div[2]/form/div/div/div/div/div[2]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4157a9a2-f502-45d7-8a95-83f7f9e39c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>5fed810e-3bdd-4aac-a869-5baa676ed67f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-select-dropdown --positon-bottom</value>
      <webElementGuid>57860a9c-263b-4ee6-9a6d-72523350c341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>995f90d2-b6be-477b-9908-f620f3ae5703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Select --AFN - Afghanistan AfghaniALL - Albanian LekANG - NL Antillian GuilderAOR - Angolan New KwanzaARP - Argentina PesosARS - Argentine PesoAUD - Australian DollarAWG - Aruban FlorinBBD - Barbados DollarBDT - Bangladeshi TakaBGL - Bulgarian LevBHD - Bahraini DinarBIF - Burundi FrancBMD - Bermudian DollarBND - Brunei DollarBOB - Bolivian BolivianoBRL - Brazilian RealBSD - Bahamian DollarBTN - Bhutan NgultrumBWP - Botswana PulaBZD - Belize DollarCAD - Canadian DollarCHF - Swiss FrancCLP - Chilean PesoCNY - Chinese Yuan RenminbiCOP - Colombian PesoCRC - Costa Rican ColonCUP - Cuban PesoCVE - Cape Verde EscudoCYP - Cyprus PoundCZK - Czech KorunaDJF - Djibouti FrancDKK - Danish KronaDOP - Dominican PesoDZD - Algerian DinarECS - Ecuador SucreEEK - Estonian KronaEGP - Egyptian PoundETB - Ethiopian BirrEUR - EuroFJD - Fiji DollarFKP - Falkland Islands PoundGBP - Pound SterlingGHC - Ghanaian CediGIP - Gibraltar PoundGMD - Gambian DalasiGNF - Guinea FrancGTQ - Guatemalan QuetzalGYD - Guyanan DollarHKD - Hong Kong DollarHNL - Honduran LempiraHRK - Croatian KunaHTG - Haitian GourdeHUF - Hungarian ForintIDR - Indonesian RupiahILS - Israeli New ShekelINR - Indian RupeeIQD - Iraqi DinarIRR - Iranian RialISK - Iceland KronaJMD - Jamaican DollarJOD - Jordanian DinarJPY - Japanese YenKES - Kenyan ShillingKHR - Kampuchean RielKMF - Comoros FrancKPW - North Korean WonKRW - Korean WonKWD - Kuwaiti DinarKYD - Cayman Islands DollarKZT - Kazakhstan TengeLAK - Lao KipLBP - Lebanese PoundLKR - Sri Lanka RupeeLRD - Liberian DollarLSL - Lesotho LotiLTL - Lithuanian LitasLVL - Latvian LatsLYD - Libyan DinarMAD - Moroccan DirhamMGF - Malagasy FrancMMK - Myanmar KyatMNT - Mongolian TugrikMOP - Macau PatacaMRO - Mauritanian OuguiyaMTL - Maltese LiraMUR - Mauritius RupeeMVR - Maldive RufiyaaMWK - Malawi KwachaMXN - Mexican New PesoMXP - Mexican PesoMYR - Malaysian RinggitMZM - Mozambique MeticalNAD - Namibia DollarNGN - Nigerian NairaNIO - Nicaraguan Cordoba OroNOK - Norwegian KronaNPR - Nepalese RupeeNZD - New Zealand DollarOMR - Omani RialPAB - Panamanian BalboaPEN - Peruvian Nuevo SolPGK - Papua New Guinea KinaPHP - Philippine PesoPKR - Pakistan RupeePLN - Polish ZlotyPYG - Paraguay GuaraniQAR - Qatari RialROL - Romanian LeuRUB - Russian RoubleRUR - Russia RublesSAR - Saudi Arabia RiyalSBD - Solomon Islands DollarSCR - Seychelles RupeeSDD - Sudanese DinarSDP - Sudanese PoundSEK - Swedish KronaSGD - Singapore DollarSHP - St. Helena PoundSKK - Slovak KorunaSLL - Sierra Leone LeoneSOS - Somali ShillingSRD - Surinamese DollarSTD - Sao Tome/Principe DobraSVC - El Salvador ColonSYP - Syrian PoundSZL - Swaziland LilangeniTHB - Thai BahtTND - Tunisian DinarTOP - Tongan Pa'angaTRL - Turkish LiraTTD - Trinidad/Tobago DollarTWD - Taiwan DollarTZS - Tanzanian ShillingUAH - Ukraine HryvniaUGX - Uganda ShillingUSD - United States DollarUYP - Uruguayan PesoVEB - Venezuelan BolivarVND - Vietnamese DongVUV - Vanuatu VatuWST - Samoan TalaXAF - CFA Franc BEACXAG - Silver (oz.)XAU - Gold (oz.)XCD - Eastern Caribbean DollarsXDR - IMF Special Drawing RightXOF - CFA Franc BCEAOXPD - Palladium (oz.)XPF - CFP FrancXPT - Platinum (oz.)YER - Yemeni RiyalYUM - Yugoslavian DinarYUN - Yugoslav DinarZAR - South African RandZMK - Zambian KwachaZRN - New ZaireZWD - Zimbabwe Dollar</value>
      <webElementGuid>f6bdc95a-d3c0-4c41-a018-ba24a01e3540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-card-container&quot;]/form[@class=&quot;oxd-form&quot;]/div[@class=&quot;oxd-form-row&quot;]/div[@class=&quot;oxd-grid-2 orangehrm-full-width-grid&quot;]/div[@class=&quot;oxd-grid-item oxd-grid-item--gutters&quot;]/div[@class=&quot;oxd-input-group oxd-input-field-bottom-space&quot;]/div[2]/div[@class=&quot;oxd-select-wrapper&quot;]/div[@class=&quot;oxd-select-dropdown --positon-bottom&quot;]</value>
      <webElementGuid>df601749-69f5-4122-8ea0-e78818541e01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div[2]/form/div/div/div/div/div[2]/div/div[2]</value>
      <webElementGuid>14fc430d-f8b1-4003-a33c-2cd6a9ddcee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Select --'])[1]/following::div[2]</value>
      <webElementGuid>5d32e1df-f7ae-4d38-8a09-84856578a219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currency'])[1]/following::div[6]</value>
      <webElementGuid>5bb08071-0e68-47df-b3fb-b454126777bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/div[2]</value>
      <webElementGuid>e415ffbb-bac0-4176-b26b-b17896f16422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;-- Select --AFN - Afghanistan AfghaniALL - Albanian LekANG - NL Antillian GuilderAOR - Angolan New KwanzaARP - Argentina PesosARS - Argentine PesoAUD - Australian DollarAWG - Aruban FlorinBBD - Barbados DollarBDT - Bangladeshi TakaBGL - Bulgarian LevBHD - Bahraini DinarBIF - Burundi FrancBMD - Bermudian DollarBND - Brunei DollarBOB - Bolivian BolivianoBRL - Brazilian RealBSD - Bahamian DollarBTN - Bhutan NgultrumBWP - Botswana PulaBZD - Belize DollarCAD - Canadian DollarCHF - Swiss FrancCLP - Chilean PesoCNY - Chinese Yuan RenminbiCOP - Colombian PesoCRC - Costa Rican ColonCUP - Cuban PesoCVE - Cape Verde EscudoCYP - Cyprus PoundCZK - Czech KorunaDJF - Djibouti FrancDKK - Danish KronaDOP - Dominican PesoDZD - Algerian DinarECS - Ecuador SucreEEK - Estonian KronaEGP - Egyptian PoundETB - Ethiopian BirrEUR - EuroFJD - Fiji DollarFKP - Falkland Islands PoundGBP - Pound SterlingGHC - Ghanaian CediGIP - Gibraltar PoundGMD - Gambian DalasiGNF - Guinea FrancGTQ - Guatemalan QuetzalGYD - Guyanan DollarHKD - Hong Kong DollarHNL - Honduran LempiraHRK - Croatian KunaHTG - Haitian GourdeHUF - Hungarian ForintIDR - Indonesian RupiahILS - Israeli New ShekelINR - Indian RupeeIQD - Iraqi DinarIRR - Iranian RialISK - Iceland KronaJMD - Jamaican DollarJOD - Jordanian DinarJPY - Japanese YenKES - Kenyan ShillingKHR - Kampuchean RielKMF - Comoros FrancKPW - North Korean WonKRW - Korean WonKWD - Kuwaiti DinarKYD - Cayman Islands DollarKZT - Kazakhstan TengeLAK - Lao KipLBP - Lebanese PoundLKR - Sri Lanka RupeeLRD - Liberian DollarLSL - Lesotho LotiLTL - Lithuanian LitasLVL - Latvian LatsLYD - Libyan DinarMAD - Moroccan DirhamMGF - Malagasy FrancMMK - Myanmar KyatMNT - Mongolian TugrikMOP - Macau PatacaMRO - Mauritanian OuguiyaMTL - Maltese LiraMUR - Mauritius RupeeMVR - Maldive RufiyaaMWK - Malawi KwachaMXN - Mexican New PesoMXP - Mexican PesoMYR - Malaysian RinggitMZM - Mozambique MeticalNAD - Namibia DollarNGN - Nigerian NairaNIO - Nicaraguan Cordoba OroNOK - Norwegian KronaNPR - Nepalese RupeeNZD - New Zealand DollarOMR - Omani RialPAB - Panamanian BalboaPEN - Peruvian Nuevo SolPGK - Papua New Guinea KinaPHP - Philippine PesoPKR - Pakistan RupeePLN - Polish ZlotyPYG - Paraguay GuaraniQAR - Qatari RialROL - Romanian LeuRUB - Russian RoubleRUR - Russia RublesSAR - Saudi Arabia RiyalSBD - Solomon Islands DollarSCR - Seychelles RupeeSDD - Sudanese DinarSDP - Sudanese PoundSEK - Swedish KronaSGD - Singapore DollarSHP - St. Helena PoundSKK - Slovak KorunaSLL - Sierra Leone LeoneSOS - Somali ShillingSRD - Surinamese DollarSTD - Sao Tome/Principe DobraSVC - El Salvador ColonSYP - Syrian PoundSZL - Swaziland LilangeniTHB - Thai BahtTND - Tunisian DinarTOP - Tongan Pa&quot; , &quot;'&quot; , &quot;angaTRL - Turkish LiraTTD - Trinidad/Tobago DollarTWD - Taiwan DollarTZS - Tanzanian ShillingUAH - Ukraine HryvniaUGX - Uganda ShillingUSD - United States DollarUYP - Uruguayan PesoVEB - Venezuelan BolivarVND - Vietnamese DongVUV - Vanuatu VatuWST - Samoan TalaXAF - CFA Franc BEACXAG - Silver (oz.)XAU - Gold (oz.)XCD - Eastern Caribbean DollarsXDR - IMF Special Drawing RightXOF - CFA Franc BCEAOXPD - Palladium (oz.)XPF - CFP FrancXPT - Platinum (oz.)YER - Yemeni RiyalYUM - Yugoslavian DinarYUN - Yugoslav DinarZAR - South African RandZMK - Zambian KwachaZRN - New ZaireZWD - Zimbabwe Dollar&quot;) or . = concat(&quot;-- Select --AFN - Afghanistan AfghaniALL - Albanian LekANG - NL Antillian GuilderAOR - Angolan New KwanzaARP - Argentina PesosARS - Argentine PesoAUD - Australian DollarAWG - Aruban FlorinBBD - Barbados DollarBDT - Bangladeshi TakaBGL - Bulgarian LevBHD - Bahraini DinarBIF - Burundi FrancBMD - Bermudian DollarBND - Brunei DollarBOB - Bolivian BolivianoBRL - Brazilian RealBSD - Bahamian DollarBTN - Bhutan NgultrumBWP - Botswana PulaBZD - Belize DollarCAD - Canadian DollarCHF - Swiss FrancCLP - Chilean PesoCNY - Chinese Yuan RenminbiCOP - Colombian PesoCRC - Costa Rican ColonCUP - Cuban PesoCVE - Cape Verde EscudoCYP - Cyprus PoundCZK - Czech KorunaDJF - Djibouti FrancDKK - Danish KronaDOP - Dominican PesoDZD - Algerian DinarECS - Ecuador SucreEEK - Estonian KronaEGP - Egyptian PoundETB - Ethiopian BirrEUR - EuroFJD - Fiji DollarFKP - Falkland Islands PoundGBP - Pound SterlingGHC - Ghanaian CediGIP - Gibraltar PoundGMD - Gambian DalasiGNF - Guinea FrancGTQ - Guatemalan QuetzalGYD - Guyanan DollarHKD - Hong Kong DollarHNL - Honduran LempiraHRK - Croatian KunaHTG - Haitian GourdeHUF - Hungarian ForintIDR - Indonesian RupiahILS - Israeli New ShekelINR - Indian RupeeIQD - Iraqi DinarIRR - Iranian RialISK - Iceland KronaJMD - Jamaican DollarJOD - Jordanian DinarJPY - Japanese YenKES - Kenyan ShillingKHR - Kampuchean RielKMF - Comoros FrancKPW - North Korean WonKRW - Korean WonKWD - Kuwaiti DinarKYD - Cayman Islands DollarKZT - Kazakhstan TengeLAK - Lao KipLBP - Lebanese PoundLKR - Sri Lanka RupeeLRD - Liberian DollarLSL - Lesotho LotiLTL - Lithuanian LitasLVL - Latvian LatsLYD - Libyan DinarMAD - Moroccan DirhamMGF - Malagasy FrancMMK - Myanmar KyatMNT - Mongolian TugrikMOP - Macau PatacaMRO - Mauritanian OuguiyaMTL - Maltese LiraMUR - Mauritius RupeeMVR - Maldive RufiyaaMWK - Malawi KwachaMXN - Mexican New PesoMXP - Mexican PesoMYR - Malaysian RinggitMZM - Mozambique MeticalNAD - Namibia DollarNGN - Nigerian NairaNIO - Nicaraguan Cordoba OroNOK - Norwegian KronaNPR - Nepalese RupeeNZD - New Zealand DollarOMR - Omani RialPAB - Panamanian BalboaPEN - Peruvian Nuevo SolPGK - Papua New Guinea KinaPHP - Philippine PesoPKR - Pakistan RupeePLN - Polish ZlotyPYG - Paraguay GuaraniQAR - Qatari RialROL - Romanian LeuRUB - Russian RoubleRUR - Russia RublesSAR - Saudi Arabia RiyalSBD - Solomon Islands DollarSCR - Seychelles RupeeSDD - Sudanese DinarSDP - Sudanese PoundSEK - Swedish KronaSGD - Singapore DollarSHP - St. Helena PoundSKK - Slovak KorunaSLL - Sierra Leone LeoneSOS - Somali ShillingSRD - Surinamese DollarSTD - Sao Tome/Principe DobraSVC - El Salvador ColonSYP - Syrian PoundSZL - Swaziland LilangeniTHB - Thai BahtTND - Tunisian DinarTOP - Tongan Pa&quot; , &quot;'&quot; , &quot;angaTRL - Turkish LiraTTD - Trinidad/Tobago DollarTWD - Taiwan DollarTZS - Tanzanian ShillingUAH - Ukraine HryvniaUGX - Uganda ShillingUSD - United States DollarUYP - Uruguayan PesoVEB - Venezuelan BolivarVND - Vietnamese DongVUV - Vanuatu VatuWST - Samoan TalaXAF - CFA Franc BEACXAG - Silver (oz.)XAU - Gold (oz.)XCD - Eastern Caribbean DollarsXDR - IMF Special Drawing RightXOF - CFA Franc BCEAOXPD - Palladium (oz.)XPF - CFP FrancXPT - Platinum (oz.)YER - Yemeni RiyalYUM - Yugoslavian DinarYUN - Yugoslav DinarZAR - South African RandZMK - Zambian KwachaZRN - New ZaireZWD - Zimbabwe Dollar&quot;))]</value>
      <webElementGuid>6cacf56a-ec60-42ea-ba78-ed997b60dd78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
