<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>list_UsernameRecords</name>
   <tag></tag>
   <elementGuidId>fd3e9be2-acac-49de-bee4-55cfc46e6ed9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.orangehrm-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div[2]/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ea5be9be-a4f3-46a7-ab48-3868aa3f425f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-container</value>
      <webElementGuid>02c6fdc8-e19f-49d8-8f04-f93a0bc5d758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UsernameAscendingDescendingUser RoleAscendingDescendingEmployee NameAscendingDescendingStatusAscendingDescendingActionsAdminAdminPaul CollingsEnabledAlice.DuvalESSAlice DuvalEnabledAnthony.NolanESSAnthony NolanEnabledCassidy.HopeESSCassidy HopeEnabledCecil.BonaparteESSCecil BonaparteEnabledCharlie.CarterESSCharlie CarterEnabledCheekuAdminVirat KohliEnabledChenzira.ChukiESSChenzira ChukiEnabledDavid.MorrisESSDavid MorrisEnabledDominic.ChaseAdminDominic ChaseEnabledEhioze.EboESSEhioze EboEnabledFiona.GraceESSFiona GraceEnabledGarry.WhiteESSGarry WhiteEnabledGoutam.GaneshESSGoutam GaneshEnabledJacqueline.WhiteESSJacqueline WhiteEnabledJadey78931ESSJade DoEnabledJadey95188ESSJade DoEnabledJadine.JackieESSJadine JackieEnabledJasmine.MorganESSJasmine MorganEnabledJoe.RootESSJoe RootEnabledJohn.SmithAdminJohn SmithEnabledJordan.MathewsESSJordan MathewsEnabledKevin.MathewsESSKevin MathewsEnabledKiyara.HuESSKiyara HuEnabledLinda.AndersonAdminLinda AndersonEnabledLisa.AndrewsESSLisa AndrewsEnabledLuke.WrightESSLuke WrightEnabledMaggie.ManningESSMaggie ManningEnabledMelan.PeirisESSMelan PeirisEnabledNathan.ElliotESSNathan ElliotEnabledNina.PatelESSNina PatelEnabledOdis.AdalwinAdminOdis AdalwinEnabledPeter.AndersonAdminPeter AndersonEnabledRebecca.HarmonyESSRebecca HarmonyEnabledRussel.HamiltonESSRussel HamiltonEnabledSania.ShaheenESSSania ShaheenEnabledSara.TencradyESSSara TencradyEnabled</value>
      <webElementGuid>bceccbc2-d022-410f-b1d2-57a0b1e3656a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]/div[@class=&quot;orangehrm-paper-container&quot;]/div[@class=&quot;orangehrm-container&quot;]</value>
      <webElementGuid>62b6e86c-c332-486f-b4dc-f1aa44292fd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div[2]/div[3]</value>
      <webElementGuid>b13febb9-c7d7-4308-9421-9a48fea8d1f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[3]</value>
      <webElementGuid>dc1a1cfd-9d1c-4bef-bdc6-20c8098df65a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'UsernameAscendingDescendingUser RoleAscendingDescendingEmployee NameAscendingDescendingStatusAscendingDescendingActionsAdminAdminPaul CollingsEnabledAlice.DuvalESSAlice DuvalEnabledAnthony.NolanESSAnthony NolanEnabledCassidy.HopeESSCassidy HopeEnabledCecil.BonaparteESSCecil BonaparteEnabledCharlie.CarterESSCharlie CarterEnabledCheekuAdminVirat KohliEnabledChenzira.ChukiESSChenzira ChukiEnabledDavid.MorrisESSDavid MorrisEnabledDominic.ChaseAdminDominic ChaseEnabledEhioze.EboESSEhioze EboEnabledFiona.GraceESSFiona GraceEnabledGarry.WhiteESSGarry WhiteEnabledGoutam.GaneshESSGoutam GaneshEnabledJacqueline.WhiteESSJacqueline WhiteEnabledJadey78931ESSJade DoEnabledJadey95188ESSJade DoEnabledJadine.JackieESSJadine JackieEnabledJasmine.MorganESSJasmine MorganEnabledJoe.RootESSJoe RootEnabledJohn.SmithAdminJohn SmithEnabledJordan.MathewsESSJordan MathewsEnabledKevin.MathewsESSKevin MathewsEnabledKiyara.HuESSKiyara HuEnabledLinda.AndersonAdminLinda AndersonEnabledLisa.AndrewsESSLisa AndrewsEnabledLuke.WrightESSLuke WrightEnabledMaggie.ManningESSMaggie ManningEnabledMelan.PeirisESSMelan PeirisEnabledNathan.ElliotESSNathan ElliotEnabledNina.PatelESSNina PatelEnabledOdis.AdalwinAdminOdis AdalwinEnabledPeter.AndersonAdminPeter AndersonEnabledRebecca.HarmonyESSRebecca HarmonyEnabledRussel.HamiltonESSRussel HamiltonEnabledSania.ShaheenESSSania ShaheenEnabledSara.TencradyESSSara TencradyEnabled' or . = 'UsernameAscendingDescendingUser RoleAscendingDescendingEmployee NameAscendingDescendingStatusAscendingDescendingActionsAdminAdminPaul CollingsEnabledAlice.DuvalESSAlice DuvalEnabledAnthony.NolanESSAnthony NolanEnabledCassidy.HopeESSCassidy HopeEnabledCecil.BonaparteESSCecil BonaparteEnabledCharlie.CarterESSCharlie CarterEnabledCheekuAdminVirat KohliEnabledChenzira.ChukiESSChenzira ChukiEnabledDavid.MorrisESSDavid MorrisEnabledDominic.ChaseAdminDominic ChaseEnabledEhioze.EboESSEhioze EboEnabledFiona.GraceESSFiona GraceEnabledGarry.WhiteESSGarry WhiteEnabledGoutam.GaneshESSGoutam GaneshEnabledJacqueline.WhiteESSJacqueline WhiteEnabledJadey78931ESSJade DoEnabledJadey95188ESSJade DoEnabledJadine.JackieESSJadine JackieEnabledJasmine.MorganESSJasmine MorganEnabledJoe.RootESSJoe RootEnabledJohn.SmithAdminJohn SmithEnabledJordan.MathewsESSJordan MathewsEnabledKevin.MathewsESSKevin MathewsEnabledKiyara.HuESSKiyara HuEnabledLinda.AndersonAdminLinda AndersonEnabledLisa.AndrewsESSLisa AndrewsEnabledLuke.WrightESSLuke WrightEnabledMaggie.ManningESSMaggie ManningEnabledMelan.PeirisESSMelan PeirisEnabledNathan.ElliotESSNathan ElliotEnabledNina.PatelESSNina PatelEnabledOdis.AdalwinAdminOdis AdalwinEnabledPeter.AndersonAdminPeter AndersonEnabledRebecca.HarmonyESSRebecca HarmonyEnabledRussel.HamiltonESSRussel HamiltonEnabledSania.ShaheenESSSania ShaheenEnabledSara.TencradyESSSara TencradyEnabled')]</value>
      <webElementGuid>96a47931-d676-46c7-ab58-5af4425afd61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
