<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>list_Currencies</name>
   <tag></tag>
   <elementGuidId>5134229f-bb55-4265-8102-a775c1c87678</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.orangehrm-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div[2]/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a5dfd38f-ca04-4fbc-8d6b-0e175576d840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-container</value>
      <webElementGuid>485e5f98-a793-4720-bbdf-f56adeeacb5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CurrencyMinimum SalaryMaximum SalaryActionsAfghanistan Afghani150.001500.00Albanian Lek150.001400.00Utd. Arab Emir. Dirham150.001500.00</value>
      <webElementGuid>131f3a17-1ae1-472c-8e38-8cb0000f5a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]/div[@class=&quot;orangehrm-paper-container&quot;]/div[@class=&quot;orangehrm-container&quot;]</value>
      <webElementGuid>cc8430ed-aeed-4d63-9ee4-c8d7b9ce7fdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div[2]/div/div[3]</value>
      <webElementGuid>e4343806-9bbf-48f5-bb90-c17c6b146c56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]</value>
      <webElementGuid>1fa35b9b-f08c-48e8-a38e-26b58a2ab4c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'CurrencyMinimum SalaryMaximum SalaryActionsAfghanistan Afghani150.001500.00Albanian Lek150.001400.00Utd. Arab Emir. Dirham150.001500.00' or . = 'CurrencyMinimum SalaryMaximum SalaryActionsAfghanistan Afghani150.001500.00Albanian Lek150.001400.00Utd. Arab Emir. Dirham150.001500.00')]</value>
      <webElementGuid>d441a6d8-91a0-4abc-b24f-b7844b5a70ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
